# Generated by Django 5.1.7 on 2025-05-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_for',
            field=models.CharField(default='all', max_length=15),
        ),
    ]
