# Generated by Django 5.1.7 on 2025-05-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
        ('store', 'add_payment_mode'),
    ]

    operations = [
    ]
