# Generated by Django 5.1.7 on 2025-05-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_payment_mode_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_mode',
        ),
    ]
